# --- Winnow data loading configuration ---

_target_: winnow.datasets.data_loaders.WinnowDatasetLoader

residue_masses: ${residue_masses}
# The internal Winnow dataset loader does not need a residue remapping
# since it uses the UNIMOD tokens directly.
residue_remapping: null
